### ISSUE TITLE
Instructions 

### ISSUE THREAD

**Issue by ShalokShalom** [TheGag96/pokemods#1]
Hi there :) 

Thanks for uploading this!

Do you mind adding short instructions, on how to build, and maybe use this? 

Thanks

**Comment by TheGag96** [comment]
Yes, I probably ought to do that... Sorry if it's been obtuse. In the meantime, should be easy enough to build with dub, the project manager for the D language. You'll need the program knarc in the same folder as the executable. You should be able to start a project using `pokemods init somerom.nds`. Which game are you trying to use this with, by the way?

Also, sorry in advance if you don't give enough command-line arguments and the program calls you an "idiot". That was a placeholder message directed at me, not you lol!

**Comment by TheGag96** [comment]
Check the latest commit. There's now a `README.md` with some helpful instructions. Let me know if you need anything else!
